create database EXERCISE2;
CREATE TABLE CONTACT_TABLE(
ID INT,
EMAIL VARCHAR(50),
FNAME VARCHAR(50),
INAME VARCHAR(50),
COMPANY VARCHAR(50),
ACTIVE_FLAG INT,
OPT_OUT INT
);

INSERT INTO CONTACT_TABLE VALUES
(123,"a@a.com","KIAN","SETH","ABC",1,1),
(133,"b@a.com","NEHA","SETH","ABC",1,0),
(234,"c@c.com","PURU","MALIK","CDF",0,0),
(342,"d@d.com","SID","MAAN","TEG",1,0);

SELECT * FROM CONTACT_TABLE;
-- SELECTING ALL COLUMNS FROM THE CONTACT TABLE WHERE THE ACTIVE FALG=1
SELECT * FROM CONTACT_TABLE WHERE ACTIVE_FLAG=1;
-- DEACTIVATE CONTACTS WHO ARE OPTED OUT
DELETE FROM CONTACT_TABLE WHERE OPT_OUT=1;


-- DELETE ALL CONTACTS WHO HAVE COMPANY NAME AS 'ABC'
DELETE FROM CONTACT_TABLE WHERE COMPANY="ABC";
-- INSERT A NER ROW WITH ID = 658,NAME='MILI',EMAIL='mili@gmail.com',COMPANY='DFH',ACTIVE_FLAG=1,OPTFLAG=1
INSERT INTO CONTACT_TABLE VALUES
(658,"mili@gmail.com","MILI",NULL,'DGH',1,1);
-- PULL OUT THE UNIQUE VALUES OF THE COMPANY COLUMN
SELECT DISTINCT COMPANY FROM CONTACT_TABLE;
-- UPDATE NAME 'MILI' TO 'NITI'
UPDATE CONTACT_TABLE SET FNAME='NITI' WHERE FNAME='MILI';
