CREATE DATABASE CONSULTATION;
CREATE TABLE DOCTOR(
ID INT PRIMARY KEY NOT NULL,
NAME VARCHAR(50) NOT NULL,
SPECIALISATION VARCHAR(50) NOT NULL,
HOSPITAL VARCHAR(50) NOT NULL,
SHIFT INT NOT NULL
);
CREATE TABLE APPOINTMENTS(
DOCTOR_NAME VARCHAR(50) NOT NULL,
APPOINTMENT_DATE DATE NOT NULL,
APPOINTMENT_TIME TIME PRIMARY KEY NOT NULL
);
CREATE TABLE PATIENT(
PATIENT_ID INT PRIMARY KEY NOT NULL,
APPOINTMENT_DATE1 DATE NOT NULL,
APPOINTMENT_TIME1 TIME NOT NULL,
DISEASE VARCHAR(50) NOT NULL,
DOCTOR_NAME VARCHAR(50)  NOT NULL
);


CREATE TABLE REVIEWS(
DOCTOR_NAME VARCHAR(50) NOT NULL,
PATIENT_ID INT PRIMARY KEY NOT NULL,
RATING INT NOT NULL,
REMARK VARCHAR(100) NOT NULL
)